name: react deploy

on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: /home/ubuntu/2025action

    steps:
      - name: ssh to ec2
        # ec2 접속 프로그램(고정)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ env.REMOTE_DIR }}
            git config --global --add safe.directory /home/ubuntu/2025action
            git pull
            npm ci
            npm run build
